// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvrzzrsqqsmmewprcsvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2cnp6cnNxcXNtbWV3cHJjc3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODg3NzIsImV4cCI6MjA2NDc2NDc3Mn0.qoeGZwdzcJlXkVC7swCGtbAoJisW5XOaVpPniR_IXaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);