// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntryfhmfncbcjgfyqnot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cnlmaG1mbmNiY2pnZnlxbm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTE0NjgsImV4cCI6MjA2NDc4NzQ2OH0.Pdkoyl0miSOsUk_HFcWM-fqvsy5EFw5epajMo6TO7vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);